### ISSUE TITLE
fake-factory in requirements.txt (production.txt) raises ImportError in pyshard_demo.py

### ISSUE THREAD

**Issue by drocpdp** [lgiordani/pyshard#1]
Looks like fake-factory is deprecated.

`
Traceback (most recent call last):
  File "pyshard_demo.py", line 3, in <module>
    from faker import Faker
  File "/Users/davideynon/Projects/virtualenvs/pyshard/lib/python3.8/site-packages/faker/__init__.py", line 7, in <module>
    raise ImportError(error)
ImportError: The ``fake-factory`` package is now called ``Faker``.
Please update your requirements.
`

Change https://github.com/lgiordani/pyshard/blob/master/requirements/production.txt from 
`fake-factory`
to
`Faker`
and it appears to work again.

I can fork, submit a PR but probably easier for you to do it on your end. Let me know, though, if you want me to do this for you.

**Comment by drocpdp** [comment]
Nice work by the way! Glad I discovered it!

**Comment by lgiordani** [comment]
Hi! Apologies for the late answer. Well, you unearthed a project that I left completely unattended! Thanks for submitting the issue and the PR, I'll merge that asap, and maybe have a look at the project, it has been left without love for ages :scream_cat:

**Comment by lgiordani** [comment]
Solved with #2
